name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
      - uses: actions/checkout@v2

      - name: ğŸ”§ Install and Audit
        run: yarn && yarn audit

      - name: ğŸš¨ Lint
        run: yarn lint

      - name: ğŸ— Build
        run: yarn clean && yarn build

      - name: âœ… Test
        run: yarn test

      - name: ğŸ“ Document
        run: yarn doc

      - name: ğŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs
